/** From gatech.edu/academics/all-degree-programs. */
export const DEGREE_PROGRAMS = {
  bachelors: [
    "Aerospace Engineering",
    "Applied Languages and Intercultural Studies",
    "Applied Physics",
    "Architecture",
    "Arts, Entertainment, and Creative Technologies",
    "Astrophysics",
    "Atmospheric and Oceanic Sciences",
    "Biochemistry",
    "Biology",
    "Biomedical Engineering",
    "Business Administration",
    "Chemical and Biomolecular Engineering",
    "Chemistry",
    "Civil Engineering",
    "Computational Media",
    "Computer Engineering",
    "Computer Science",
    "Construction Science and Management",
    "Economics",
    "Economics and International Affairs",
    "Electrical Engineering",
    "Environmental Engineering",
    "Environmental Science",
    "Global Economics and Modern Languages",
    "History, Technology, and Society",
    "Industrial Design",
    "Industrial Engineering",
    "International Affairs",
    "International Affairs and Modern Languages",
    "Literature, Media, and Communication",
    "Materials Science and Engineering",
    "Mathematics",
    "Mathematics and Computing",
    "Mechanical Engineering",
    "Music Technology",
    "Neuroscience",
    "Nuclear and Radiological Engineering",
    "Physics",
    "Psychology",
    "Public Policy",
    "Solid Earth and Planetary Sciences",
    "Urban Planning and Spatial Analytics",
  ],
  masters: [
    "Aerospace Engineering",
    "Analytics",
    "Applied Languages and Intercultural Studies",
    "Applied Systems Engineering",
    "Architecture",
    "Bioengineering",
    "Bioinformatics",
    "Biology",
    "Biomedical Engineering",
    "Biomedical Innovation and Development",
    "Building Construction and Facility Management",
    "Business Administration",
    "Chemical Engineering",
    "Chemistry",
    "City and Regional Planning",
    "Civil Engineering",
    "Computational Science and Engineering",
    "Computer Science",
    "Cybersecurity",
    "Digital Media",
    "Earth and Atmospheric Sciences",
    "Economics",
    "Electrical and Computer Engineering",
    "Engineering Science and Mechanics",
    "Environmental Engineering",
    "Geographic Information Science and Technology",
    "Global Media and Cultures",
    "Health Systems",
    "History and Sociology of Technology and Science",
    "Human-Computer Interaction",
    "Industrial Design",
    "Industrial Engineering",
    "International Affairs",
    "International Affairs, Science, and Technology",
    "International Security",
    "Management",
    "Manufacturing Leadership",
    "Materials Science and Engineering",
    "Mathematics",
    "Mechanical Engineering",
    "Medical Physics",
    "Music Technology",
    "Nuclear Engineering",
    "Occupational Safety and Health",
    "Operations Research",
    "Physics",
    "Psychology",
    "Public Policy",
    "Quantitative and Computational Finance",
    "Real Estate Development",
    "Robotics",
    "Statistics",
    "Supply Chain Engineering",
    "Sustainability Energy and Environmental Management",
    "Urban Analytics",
    "Urban Design",
  ],
  doctoral: [
    "Aerospace Engineering",
    "Algorithms, Combinatorics, and Optimization",
    "Applied Physiology",
    "Architecture",
    "Bioengineering",
    "Bioinformatics",
    "Biology",
    "Biomedical Engineering",
    "Building Construction",
    "Chemical Engineering",
    "Chemistry",
    "City and Regional Planning",
    "Civil Engineering",
    "Computational Science and Engineering",
    "Computer Science",
    "Digital Media",
    "Earth and Atmospheric Sciences",
    "Economics",
    "Electrical and Computer Engineering",
    "Engineering Science and Mechanics",
    "Environmental Engineering",
    "History and Sociology of Technology and Science",
    "Human-Centered Computing",
    "Industrial Engineering",
    "International Affairs, Science, and Technology",
    "Machine Learning",
    "Management",
    "Materials Science and Engineering",
    "Mathematics",
    "Mechanical Engineering",
    "Music Technology",
    "Neuroscience and Neurotechnology",
    "Nuclear Engineering",
    "Ocean Science and Engineering",
    "Operations Research",
    "Physics",
    "Psychology",
    "Public Policy",
    "Quantitative Biosciences",
    "Robotics",
  ],
} as const;

export type DegreeLevel = keyof typeof DEGREE_PROGRAMS;

export function degreeLevel(standing: string): DegreeLevel {
  if (standing === "masters") return "masters";
  if (standing === "phd") return "doctoral";
  return "bachelors";
}
